/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChakrasRouteImport } from './routes/chakras'
import { Route as CiclosRouteImport } from './routes/ciclos'
import { Route as DiaForaDoTempoRouteImport } from './routes/dia-fora-do-tempo'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as KaiRouteImport } from './routes/kai'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedCiclosKinKinRouteImport } from './routes/_authenticated/ciclos.kin.$kin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChakrasRoute = ChakrasRouteImport.update({
  id: '/chakras',
  path: '/chakras',
  getParentRoute: () => rootRouteImport,
} as any)
const CiclosRoute = CiclosRouteImport.update({
  id: '/ciclos',
  path: '/ciclos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaForaDoTempoRoute = DiaForaDoTempoRouteImport.update({
  id: '/dia-fora-do-tempo',
  path: '/dia-fora-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const KaiRoute = KaiRouteImport.update({
  id: '/kai',
  path: '/kai',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCiclosKinKinRoute =
  AuthenticatedCiclosKinKinRouteImport.update({
    id: '/ciclos/kin/$kin',
    path: '/ciclos/kin/$kin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chakras': typeof ChakrasRoute
  '/ciclos': typeof CiclosRoute
  '/dia-fora-do-tempo': typeof DiaForaDoTempoRoute
  '/jornada': typeof JornadaRoute
  '/kai': typeof KaiRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ciclos/kin/$kin': typeof AuthenticatedCiclosKinKinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chakras': typeof ChakrasRoute
  '/ciclos': typeof CiclosRoute
  '/dia-fora-do-tempo': typeof DiaForaDoTempoRoute
  '/jornada': typeof JornadaRoute
  '/kai': typeof KaiRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ciclos/kin/$kin': typeof AuthenticatedCiclosKinKinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chakras': typeof ChakrasRoute
  '/ciclos': typeof CiclosRoute
  '/dia-fora-do-tempo': typeof DiaForaDoTempoRoute
  '/jornada': typeof JornadaRoute
  '/kai': typeof KaiRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/ciclos/kin/$kin': typeof AuthenticatedCiclosKinKinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chakras'
    | '/ciclos'
    | '/dia-fora-do-tempo'
    | '/jornada'
    | '/kai'
    | '/redefinir-senha'
    | '/admin'
    | '/perfil'
    | '/ciclos/kin/$kin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chakras'
    | '/ciclos'
    | '/dia-fora-do-tempo'
    | '/jornada'
    | '/kai'
    | '/redefinir-senha'
    | '/admin'
    | '/perfil'
    | '/ciclos/kin/$kin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chakras'
    | '/ciclos'
    | '/dia-fora-do-tempo'
    | '/jornada'
    | '/kai'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/_authenticated/ciclos/kin/$kin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChakrasRoute: typeof ChakrasRoute
  CiclosRoute: typeof CiclosRoute
  DiaForaDoTempoRoute: typeof DiaForaDoTempoRoute
  JornadaRoute: typeof JornadaRoute
  KaiRoute: typeof KaiRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chakras': {
      id: '/chakras'
      path: '/chakras'
      fullPath: '/chakras'
      preLoaderRoute: typeof ChakrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciclos': {
      id: '/ciclos'
      path: '/ciclos'
      fullPath: '/ciclos'
      preLoaderRoute: typeof CiclosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-fora-do-tempo': {
      id: '/dia-fora-do-tempo'
      path: '/dia-fora-do-tempo'
      fullPath: '/dia-fora-do-tempo'
      preLoaderRoute: typeof DiaForaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kai': {
      id: '/kai'
      path: '/kai'
      fullPath: '/kai'
      preLoaderRoute: typeof KaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclos/kin/$kin': {
      id: '/_authenticated/ciclos/kin/$kin'
      path: '/ciclos/kin/$kin'
      fullPath: '/ciclos/kin/$kin'
      preLoaderRoute: typeof AuthenticatedCiclosKinKinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedCiclosKinKinRoute: typeof AuthenticatedCiclosKinKinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedCiclosKinKinRoute: AuthenticatedCiclosKinKinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChakrasRoute: ChakrasRoute,
  CiclosRoute: CiclosRoute,
  DiaForaDoTempoRoute: DiaForaDoTempoRoute,
  JornadaRoute: JornadaRoute,
  KaiRoute: KaiRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
